version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "1935:1935"
    networks:
      - video-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/www/static

  janus:
    image: canyan/janus-gateway:latest
    ports:
      - "8088:8088"
      - "8089:8089"
    networks:
      - video-network
    volumes:
      - ./janus.jcfg:/opt/janus/etc/janus/janus.jcfg:ro

networks:
  video-network:
    driver: bridge

